Vendor: [ 0x41 ]
Device: [ 0x00 ]
Model:  [ 0x00, 0x00, 0x00, 0x33 ]

Command:
  query:  [ 0x11 ]
  send:   [ 0x12 ]

Amp_type:
  addr: [0x00,0x00,0x04,0x20]
  val:
    Acoustic: [ 0x00 ]
    Clean:    [ 0x01 ]
    Crunch:   [ 0x02 ]
    Lead:     [ 0x03 ]
    Brown:    [ 0x04 ]

Booster:
  addr: [0x00,0x00,0x04,0x27]
Reverb:
  addr: [0x60,0x00,0x12,0x14]
