SysEx:
  Canal:    0x00
  Gain:     0x01
  Volume:   0x02
  Bass:     0x10
  Medium:      0x11
  Treble:   0x12
  Presence: 0x13
  Reverb:   0x14
  Delay:    0x15
  Chorus:   0x16
  Boost:    0x17
  Modulation: 0x18
  Fx Loop:  0x19
  Tone Set: 0x1A
  Master Vol: 0x1B
  Pedal FX: 0x1C
  Expr Pedal: 0x1D

